name: CIT Memory And Badger

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  memory-badger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Run in-memory and badger integration tests
      run: make mem-and-badger-storage-integration-test
